[project]
name      = "luma"
directory = "src"
entry     = "src/main.lx"

[build]
flags = ""

[output]
binary_dir = "bin"

[dependencies]
exclude = [ "src/ast/ast_print.lx" ]
paths = [
  "lib/progress_bar.lx",
  "lib/color.lx",
  "lib/json.lx"
]

[run] 
args = [
  test  => "./bin/luma test/test.lx -name testing"
  build => "lumix build"
  install => "killall luma 2>/dev/null; sudo ./scripts/install.sh"
  bootstrap => "./scripts/bootstrap-build.sh"
]

[test]
valid  = [ "test/valid"  ]
errors = [ "test/errors" ]

