[project]
name      = "luma"
directory = "src"
entry     = "src/main.lx"

[output]
binary_dir = "bin"

[dependiecs]
paths = [
    ""
]

[build]
flags = "-O2 --no-sanitize"

[run]
args = "test/test.lx -l std/args.lx -name test"
